services:
  my-ollama-openrouter-proy:
    build: .
    ports:
      - 11434:11434
    restart: unless-stopped
    #user: 123:4096
    environment:
     - OPENAI_API_KEY=${OPENROUTERAI_OLLAMA_PROXY_KEY?env variable OPENAI_API_KEY must be set !!}
     - TZ=Europe/Brussels
